import { DEFAULT_CURRENCY } from "@/src/lib/currency";
import type {
  Account,
  AppNotification,
  Beneficiary,
  Device,
  Holding,
  InvestmentOrder,
  InvestmentProduct,
  PaymentCard,
  Preferences,
  SecurityState,
  Transaction,
  User,
} from "@/src/types";

const DAY = 86_400_000;

function ago(days: number, hours = 0) {
  return new Date(Date.now() - days * DAY - hours * 3_600_000).toISOString();
}

function ahead(days: number) {
  return new Date(Date.now() + days * DAY).toISOString();
}

let counter = 1000;
export function nextId(prefix: string) {
  counter += 1;
  return `${prefix}_${counter.toString(36)}${Date.now().toString(36).slice(-4)}`;
}

export function makeReference() {
  counter += 1;
  return `INV-${new Date().getFullYear()}-${counter}${Math.floor(
    Math.random() * 90 + 10,
  )}`;
}

export const seedUser: User = {
  id: "usr_1",
  fullName: "Odue Asare",
  email: "odue@inveto.app",
  phone: "+1 555 010 2288",
  avatarUri: null,
  memberSince: ago(418),
  tier: "premium",
  kycVerified: true,
};

export const seedPreferences: Preferences = {
  currency: DEFAULT_CURRENCY,
};

export const seedAccounts: Account[] = [
  {
    id: "acc_savings",
    name: "Main Savings",
    kind: "savings",
    number: "40219384756",
    balance: 24_615.4,
    currency: DEFAULT_CURRENCY,
    interestRate: 0.1425,
    openedAt: ago(410),
    frozen: false,
  },
  {
    id: "acc_current",
    name: "Current Account",
    kind: "current",
    number: "40203847596",
    balance: 6_280.75,
    currency: DEFAULT_CURRENCY,
    interestRate: 0.021,
    openedAt: ago(398),
    frozen: false,
  },
  {
    id: "acc_investment",
    name: "Investment Pot",
    kind: "investment",
    number: "40304758169",
    balance: 22_524.2,
    currency: DEFAULT_CURRENCY,
    interestRate: 0.0,
    openedAt: ago(240),
    frozen: false,
  },
];

export const seedCards: PaymentCard[] = [
  {
    id: "crd_1",
    brand: "visa",
    label: "Personal Visa",
    last4: "4417",
    expiry: "08/28",
    holder: "ODUE ASARE",
    isDefault: true,
    frozen: false,
    addedAt: ago(300),
  },
  {
    id: "crd_2",
    brand: "mastercard",
    label: "Business Mastercard",
    last4: "8820",
    expiry: "02/27",
    holder: "INVETO MEDIA LTD",
    isDefault: false,
    frozen: false,
    addedAt: ago(150),
  },
  {
    id: "crd_3",
    brand: "bank",
    label: "Everyday Checking",
    last4: "3391",
    expiry: "—",
    holder: "ODUE ASARE",
    isDefault: false,
    frozen: true,
    addedAt: ago(88),
  },
];

export const seedTransactions: Transaction[] = [
  {
    id: "txn_1",
    accountId: "acc_current",
    title: "Blue Bottle Coffee",
    description: "Coffee with Sam",
    amount: -18.75,
    currency: DEFAULT_CURRENCY,
    kind: "card",
    category: "food",
    status: "completed",
    createdAt: ago(0, 3),
    counterparty: "Blue Bottle Coffee",
    reference: makeReference(),
    cardLast4: "4417",
  },
  {
    id: "txn_2",
    accountId: "acc_savings",
    title: "Salary — Inveto Media",
    description: "Monthly payroll",
    amount: 8_400,
    currency: DEFAULT_CURRENCY,
    kind: "deposit",
    category: "salary",
    status: "completed",
    createdAt: ago(1, 2),
    counterparty: "Inveto Media Ltd",
    reference: makeReference(),
    cardLast4: null,
  },
  {
    id: "txn_3",
    accountId: "acc_current",
    title: "Uniqlo",
    description: "Clothing",
    amount: -189.0,
    currency: DEFAULT_CURRENCY,
    kind: "card",
    category: "shopping",
    status: "completed",
    createdAt: ago(2, 5),
    counterparty: "Uniqlo",
    reference: makeReference(),
    cardLast4: "4417",
  },
  {
    id: "txn_4",
    accountId: "acc_investment",
    title: "91-Day Treasury Bill",
    description: "Buy 91-day bill",
    amount: -3_000,
    currency: DEFAULT_CURRENCY,
    kind: "investment",
    category: "investment",
    status: "completed",
    createdAt: ago(4),
    counterparty: "Direct Treasury",
    reference: makeReference(),
    cardLast4: null,
  },
  {
    id: "txn_5",
    accountId: "acc_current",
    title: "City Power & Light",
    description: "Electricity top-up",
    amount: -150,
    currency: DEFAULT_CURRENCY,
    kind: "card",
    category: "utilities",
    status: "pending",
    createdAt: ago(5, 1),
    counterparty: "City Power & Light",
    reference: makeReference(),
    cardLast4: "8820",
  },
  {
    id: "txn_6",
    accountId: "acc_savings",
    title: "Transfer to Kojo Mensah",
    description: "Split dinner",
    amount: -240,
    currency: DEFAULT_CURRENCY,
    kind: "transfer",
    category: "transfer",
    status: "completed",
    createdAt: ago(6, 4),
    counterparty: "Kojo Mensah",
    reference: makeReference(),
    cardLast4: null,
  },
  {
    id: "txn_7",
    accountId: "acc_savings",
    title: "Uber",
    description: "Trip",
    amount: -74.2,
    currency: DEFAULT_CURRENCY,
    kind: "card",
    category: "transport",
    status: "completed",
    createdAt: ago(8, 6),
    counterparty: "Uber",
    reference: makeReference(),
    cardLast4: "4417",
  },
  {
    id: "txn_8",
    accountId: "acc_investment",
    title: "Dividend — Atlas Energy",
    description: "Annual dividend",
    amount: 412.75,
    currency: DEFAULT_CURRENCY,
    kind: "dividend",
    category: "investment",
    status: "completed",
    createdAt: ago(12),
    counterparty: "Atlas Energy",
    reference: makeReference(),
    cardLast4: null,
  },
  {
    id: "txn_9",
    accountId: "acc_current",
    title: "Delta Coffee",
    description: "Food",
    amount: -132.4,
    currency: DEFAULT_CURRENCY,
    kind: "card",
    category: "food",
    status: "reversed",
    createdAt: ago(14),
    counterparty: "Delta Coffee",
    reference: makeReference(),
    cardLast4: "4417",
  },
  {
    id: "txn_10",
    accountId: "acc_current",
    title: "Netflix",
    description: "Subscription",
    amount: -54.0,
    currency: DEFAULT_CURRENCY,
    kind: "card",
    category: "entertainment",
    status: "completed",
    createdAt: ago(18),
    counterparty: "Netflix",
    reference: makeReference(),
    cardLast4: "4417",
  },
  {
    id: "txn_11",
    accountId: "acc_savings",
    title: "Monthly transfer to Investment",
    description: "Auto-invest",
    amount: -1_200,
    currency: DEFAULT_CURRENCY,
    kind: "transfer",
    category: "investment",
    status: "completed",
    createdAt: ago(21),
    counterparty: "Internal transfer",
    reference: makeReference(),
    cardLast4: null,
  },
  {
    id: "txn_12",
    accountId: "acc_current",
    title: "Pharmacy",
    description: "Health",
    amount: -210.75,
    currency: DEFAULT_CURRENCY,
    kind: "card",
    category: "health",
    status: "completed",
    createdAt: ago(26),
    counterparty: "Central Pharmacy",
    reference: makeReference(),
    cardLast4: "8820",
  },
  {
    id: "txn_13",
    accountId: "acc_savings",
    title: "Reversal — Delta Coffee",
    description: "Refund issued",
    amount: 132.4,
    currency: DEFAULT_CURRENCY,
    kind: "transfer",
    category: "food",
    status: "completed",
    createdAt: ago(27),
    counterparty: "Delta Coffee",
    reference: makeReference(),
    cardLast4: null,
  },
  {
    id: "txn_14",
    accountId: "acc_current",
    title: "Account fee",
    description: "Monthly maintenance",
    amount: -25,
    currency: DEFAULT_CURRENCY,
    kind: "fee",
    category: "other",
    status: "completed",
    createdAt: ago(31),
    counterparty: null,
    reference: makeReference(),
    cardLast4: null,
  },
];

export const seedProducts: InvestmentProduct[] = [
  {
    id: "prd_1",
    ticker: "T-BILL-91",
    currency: DEFAULT_CURRENCY,
    name: "91-Day Treasury Bill",
    assetClass: "treasury",
    price: 100,
    previousClose: 100,
    yieldPercent: 5.4,
    risk: "low",
    provider: "Direct Treasury",
    description:
      "A 91-day government treasury bill. Low risk, predictable yield, redeemable at par after 91 days.",
  },
  {
    id: "prd_2",
    ticker: "ETF-FIN",
    currency: DEFAULT_CURRENCY,
    name: "Global Financials ETF",
    assetClass: "etf",
    price: 148.6,
    previousClose: 146.2,
    yieldPercent: 3.8,
    risk: "medium",
    provider: "Vanguard",
    description:
      "Tracks large financial institutions across developed markets. Diversified across the sector with daily liquidity.",
  },
  {
    id: "prd_3",
    ticker: "GOLD",
    currency: DEFAULT_CURRENCY,
    name: "Physical Gold",
    assetClass: "fixed-deposit",
    price: 2_418.0,
    previousClose: 2_395.5,
    yieldPercent: 5.2,
    risk: "medium",
    provider: "Sparrow Securities",
    description:
      "Backed physical gold held offshore. A long-run hedge against currency depreciation and inflation.",
  },
  {
    id: "prd_4",
    ticker: "ATLS",
    currency: DEFAULT_CURRENCY,
    name: "Atlas Energy",
    assetClass: "equity",
    price: 12.35,
    previousClose: 11.9,
    yieldPercent: 4.1,
    risk: "high",
    provider: "NYSE",
    description:
      "Single-name equity in a listed utility. Higher volatility, suitable for a long-term growth allocation.",
  },
  {
    id: "prd_5",
    ticker: "BTC",
    currency: DEFAULT_CURRENCY,
    name: "Bitcoin",
    assetClass: "crypto",
    price: 64_200,
    previousClose: 62_500,
    yieldPercent: 41.7,
    risk: "high",
    provider: "Inveto Digital",
    description:
      "Spot bitcoin held in cold storage. Highest risk and highest volatility in the catalogue.",
  },
  {
    id: "prd_6",
    ticker: "FD-1Y",
    currency: DEFAULT_CURRENCY,
    name: "1-Year Fixed Deposit",
    assetClass: "fixed-deposit",
    price: 100,
    previousClose: 100,
    yieldPercent: 4.6,
    risk: "low",
    provider: "Inveto Bank",
    description:
      "A one-year fixed deposit. Locked for twelve months at a guaranteed rate, with early termination options.",
  },
];

export const seedHoldings: Holding[] = [
  {
    id: "hld_1",
    productId: "prd_1",
    units: 200,
    averageCost: 100,
    addedAt: ago(210),
  },
  {
    id: "hld_2",
    productId: "prd_2",
    units: 12,
    averageCost: 131.4,
    addedAt: ago(140),
  },
  {
    id: "hld_3",
    productId: "prd_4",
    units: 60,
    averageCost: 9.8,
    addedAt: ago(95),
  },
];

export const seedOrders: InvestmentOrder[] = [
  {
    id: "ord_1",
    productId: "prd_1",
    side: "buy",
    units: 200,
    price: 100,
    total: 20_000,
    fee: 40,
    status: "filled",
    createdAt: ago(210),
  },
  {
    id: "ord_2",
    productId: "prd_2",
    side: "buy",
    units: 12,
    price: 131.4,
    total: 1_576.8,
    fee: 4.72,
    status: "filled",
    createdAt: ago(140),
  },
  {
    id: "ord_3",
    productId: "prd_4",
    side: "buy",
    units: 60,
    price: 9.8,
    total: 588,
    fee: 2.94,
    status: "filled",
    createdAt: ago(95),
  },
];

export const seedBeneficiaries: Beneficiary[] = [
  {
    id: "ben_1",
    name: "Kojo Mensah",
    bank: "Inveto Bank",
    accountNumber: "40219384756",
    createdAt: ago(120),
  },
  {
    id: "ben_2",
    name: "Ama Owusu",
    bank: "Inveto Bank",
    accountNumber: "40203847596",
    createdAt: ago(60),
  },
];

export const seedNotifications: AppNotification[] = [
  {
    id: "ntf_1",
    kind: "transaction",
    title: "Card payment approved",
    body: "$18.75 at Blue Bottle Coffee with Visa •••• 4417",
    createdAt: ago(0, 3),
    read: false,
    href: "/transaction/txn_1",
  },
  {
    id: "ntf_2",
    kind: "investment",
    title: "Dividend credited",
    body: "$412.75 dividend from Atlas Energy landed in your Investment Pot.",
    createdAt: ago(0, 9),
    read: false,
    href: "/investing",
  },
  {
    id: "ntf_3",
    kind: "security",
    title: "New sign-in from iPhone 16",
    body: "London, UK · just now. If this was not you, secure your account.",
    createdAt: ago(0, 11),
    read: false,
    href: "/securitysettings",
  },
  {
    id: "ntf_4",
    kind: "transaction",
    title: "Utility top-up pending",
    body: "$150.00 is still processing and will settle within 1 business day.",
    createdAt: ago(1),
    read: true,
    href: "/transaction/txn_5",
  },
  {
    id: "ntf_5",
    kind: "system",
    title: "Statement ready",
    body: "Your January statement is available to download from Accounts.",
    createdAt: ago(3),
    read: true,
    href: "/accounts",
  },
  {
    id: "ntf_6",
    kind: "promo",
    title: "5.4% p.a. on 1-year deposits",
    body: "Lock your savings for twelve months. Available until Friday.",
    createdAt: ago(6),
    read: true,
    href: "/investing",
  },
];

export const seedDevices: Device[] = [
  {
    id: "dev_1",
    name: "iPhone 16 Pro",
    platform: "ios",
    lastActiveAt: ago(0, 0),
    current: true,
    trusted: true,
  },
  {
    id: "dev_2",
    name: "Galaxy S24",
    platform: "android",
    lastActiveAt: ago(4),
    current: false,
    trusted: true,
  },
  {
    id: "dev_3",
    name: "Chrome on macOS",
    platform: "web",
    lastActiveAt: ago(31),
    current: false,
    trusted: false,
  },
];

export const seedSecurity: SecurityState = {
  pinSet: true,
  twoFactorEnabled: false,
  biometricsEnabled: false,
  biometricsType: "face",
  autoLockSeconds: 300,
  transactionAlerts: true,
  loginAlerts: true,
  emailTransactionAlerts: true,
  emailLoginAlerts: true,
  emailSecurityAlerts: true,
  emailMarketing: false,
};

export { ahead };
